AdministradorPedidosApp/Controllers/CuponController.cs
using AdministradorPedidosApp.Data;
using AdministradorPedidosApp.Interfaces;
using AdministradorPedidosApp.Models;
using AdministradorPedidosApp.Models.DTOs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Drawing;

namespace AdministradorPedidosApp.Controllers
{
    public class CuponController : Controller
    {
        private readonly ICuponService _cuponService;
        private readonly AdministradorPedidosAppContext _context;

        public CuponController(ICuponService cuponService, AdministradorPedidosAppContext context)
        {
            _cuponService = cuponService;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var cuponModel = new List<CuponModel>();
                cuponModel = await _cuponService.Index();
                return View(cuponModel);
            }
            catch(Exception ex)
            {
                TempData["Error"] = ex.Message;
                return View();
            }
        }

        public async Task<IActionResult> Create()
        {
            try
            {
                var cuponModel = new CuponModel();

                ViewBag.Articulos = await _context.Articulos
                    .Include(a => a.Precio)
                    .Where(a => a.Activo == true
                        && a.Precio.Precio != 0)
                    .ToListAsync();
                ViewBag.CategoriasCupones = await _cuponService.TraerCategorias();
                return View(cuponModel);
            } 
            catch(Exception ex)
            {
                TempData["Error"] = ex.Message;
                return View();
            }
        }

        #region Alta o Edición de Cupón

        [HttpPost]
        public async Task<IActionResult> AltaOEditCupon([FromForm] CuponModel cupon, [FromForm] string endPoint, [FromForm] string? detalle = null,
            [FromForm] string? categoriasSeleccionadas = null, IFormFile? imagen = null)
        {
            try
            {
                var result = await _cuponService.AltaOEditCupon(cupon, endPoint, detalle, categoriasSeleccionadas, imagen);
                return Json(new { success = true, message = result });
            }
            catch(Exception ex)
            {
                return Json(new { success = false, message = ex.Message});
            }
        }

        #endregion

        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var cuponModel = await _cuponService.ObtenerCuponPorId(id);

                ViewBag.Articulos = await _cuponService.TraerArticulosSeleccionados(cuponModel);
                ViewBag.CategoriasCupones = await _cuponService.TraerCategorias();

                return View(cuponModel);
            }
            catch(Exception ex)
            {
                TempData["Error"] = ex.Message;
                return View();
            }
        }
    }
}

AdministradorPedidosApp/Views/Cupon/Create.cshtml
@model AdministradorPedidosApp.Models.CuponModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/css/cargarimagen.css" rel="stylesheet" />
<link href="~/css/modalselectcategoriasarticulos.css" rel="stylesheet" />

<div class="row">
    <div class="col-md-4">
        <form id="cuponForm">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Descripción</label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Porcentaje de Descuento</label>
                <input asp-for="PorcentajeDto" class="form-control" data-val="false" />
                <span asp-validation-for="PorcentajeDto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Inicio de Vigencia</label>
                <input asp-for="FechaInicio" class="form-control" type="date" />
                <span asp-validation-for="FechaInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Fin de Vigencia</label>
                <input asp-for="FechaFin" class="form-control" type="date" />
                <span asp-validation-for="FechaFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Tipo de Cupón</label>
                <select asp-for="TipoCupon" class="form-control" id="tipoCuponSelect">
                    <option value="DESCUENTO">Descuento</option>
                    <option value="PROMO">Promoción</option>
                </select>
                <span asp-validation-for="TipoCupon" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Activo" /> @Html.DisplayNameFor(model => model.Activo)
                </label>
            </div>

            <br />
            <div class="form-group">
                <button type="button" id="agregarArticulosBtn" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#categoriasModal">
                    Seleccionar Artículos
                </button>

            </div>
            <br />
            <div>
                <div id="dropzone" class="dropzone">
                    Arrastra y suelta la imagen aquí o haz clic para seleccionar.
                </div>
                <input type="file" id="fileInput" name="Imagen" class="form-control-file" hidden />
                <div id="previewContainer" class="preview-container"></div>
            </div>
            <br />

            <br />
            <div class="form-group">
                <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#categoriasCuponModal">
                    Seleccionar Categorías
                </button>

            </div>
            <br />

        </form>
        @Html.Partial("_ArticulosCuponPartial", Model) @*Modal para seleccionar artículos para las promociones*@

        @Html.Partial("_CuponCategoriasPartial", Model) @*Modal para seleccionar a que categorias pertenece el cupón*@

        <div class="form-group">
            <button class="btn btn-primary" id="btn-venta" onclick="altaCupon()">Crear</button>
        </div>

        <div id="error-message" style="margin-top: 5px;"></div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script src="~/js/articulos/cargarimagen.js"></script>
    <script src="~/js/articulos/searchcategoriasinmodal.js"></script>
    <script src="~/js/cupones/altaCupon.js"></script>

    <script>
        var detalles = [];
        var categoriasSeleccionadas = [];

        function agregarDetallesCupon() {
            detalles = [];

            $('#articulosTable input[type=checkbox]:checked').each(function () {
                var idArticulo = $(this).attr('id');
                var cantidad = $(this).closest('tr').find('input[type=number]').val();
                detalles.push({
                    Id_ArticuloAsociado: parseInt(idArticulo),
                    Cantidad: parseInt(cantidad)
                });
            });
            $('#articulosMoldal').modal('hide');
        }

        function agregarCategoriasAlCupon(){
            agregarCategoriasAlCupon = [];

            $('#categoriasTable input[type=checkbox]:checked').each(function () {
                var idCategoria = $(this).attr('id');
                categoriasSeleccionadas.push(parseInt(idCategoria));
            });
            console.log(categoriasSeleccionadas);
            $('#categoriasModal').modal('hide');
        }

        function altaCupon() {
            $('#error-message').text("");

            var form = document.getElementById('cuponForm');
            var formData = new FormData(form);

            formData.append('Descripcion', $('#Descripcion').val());
            formData.append('PorcentajeDto', $('#PorcentajeDto').val());
            formData.append('FechaInicio', $('#FechaInicio').val());
            formData.append('FechaFin', $('#FechaFin').val());
            formData.append('TipoCupon', document.getElementById('tipoCuponSelect').value);

            formData.append('EndPoint', 'CrearCupon');

            formData.append('Detalle', JSON.stringify(detalles));

            formData.append('CategoriasSeleccionadas', categoriasSeleccionadas);

            console.log(formData);

            $.ajax({
                url: '@Url.Action("AltaOEditCupon", "Cupon")',
                type: 'POST',
                data: formData,
                processData: false,
                contentType: false,
                success: function (response) {
                    if (response.success) {

                        window.location.href = '/Cupon/Index';
                        sessionStorage.setItem('successMessage', response.message);

                        $('#success-message').removeClass().
                            addClass('text-danger').text(response.message);

                    } else if (!response.success) {

                        $('#error-message').removeClass().
                            addClass('text-danger').text(response.message);
                    }

                },
                error: function (response) {

                    if (response.responseJSON && response.responseJSON.error) {

                        $('#error-message').removeClass().
                            addClass('text-danger').text("Error al crear el cupón.");
                    } else {

                        $('#error-message').removeClass().
                            addClass('text-danger').text("Error al crear el cupón ERROR FALSE 2.");
                    }
                }
            });
        }
    </script>
}

AdministradorPedidosApp/Views/Cupon/Edit.cshtml
@model AdministradorPedidosApp.Models.CuponModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/css/cargarimagen.css" rel="stylesheet" />
<link href="~/css/modalselectcategoriasarticulos.css" rel="stylesheet" />

<div class="row">
    <div class="col-md-4">
        <form id="cuponForm">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id_Cupon" />
            <div class="form-group">
                <label class="control-label">Descripcion</label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Porcentaje de Descuento</label>
                <input asp-for="PorcentajeDto" class="form-control" data-val="false" />
                <span asp-validation-for="PorcentajeDto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Inicio de Vigencia</label>
                <input asp-for="FechaInicio" class="form-control" type="date" />
                <span asp-validation-for="FechaInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Fin de Vigencia</label>
                <input asp-for="FechaFin" class="form-control" type="date" />
                <span asp-validation-for="FechaFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Tipo de Cupón</label>
                <select asp-for="TipoCupon" class="form-control" id="tipoCuponSelect">
                    <option value="DESCUENTO">Descuento</option>
                    <option value="PROMO">Promoción</option>
                </select>
                <span asp-validation-for="TipoCupon" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Activo" /> @Html.DisplayNameFor(model => model.Activo)
                </label>
            </div>

            <br />
            <div class="form-group">
                <button type="button" id="agregarArticulosBtn" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#categoriasModal">
                    Seleccionar Artículos
                </button>

            </div>
            <br />
            <div>
                <div id="dropzone" class="dropzone">
                    Arrastra y suelta la imagen aquí o haz clic para seleccionar.
                </div>
                <input type="file" id="fileInput" name="Imagen" class="form-control-file" hidden />
                <div id="previewContainer" class="preview-container"></div>
            </div>
            <br />

            <br />
            <div class="form-group">
                <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#categoriasCuponModal">
                    Seleccionar Categorías
                </button>

            </div>
            <br />
        </form>
        @Html.Partial("_ArticulosCuponPartialEdit", Model) @*Modal para seleccionar artículos para las promociones*@

        @Html.Partial("_CuponCategoriasPartial", Model) @*Modal para seleccionar a que categorias pertenece el cupón*@

        <div class="form-group">
            <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
            <button class="btn btn-primary" id="btn-venta" onclick="editarCupon()">Editar</button>
        </div>

        <div id="error-message" style="margin-top: 5px;"></div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script src="~/js/articulos/cargarimagen.js"></script>
    <script src="~/js/articulos/searchcategoriasinmodal.js"></script>
    <script src="~/js/cupones/altaCupon.js"></script>

    <script>
        var detalles = [];
        var categoriasSeleccionadas = [];

        function agregarDetallesCupon() {
            detalles = [];

            $('#articulosTable input[type=checkbox]:checked').each(function () {
                var idArticulo = $(this).attr('id');
                var cantidad = $(this).closest('tr').find('input[type=number]').val();
                detalles.push({
                    Id_ArticuloAsociado: parseInt(idArticulo),
                    Cantidad: parseInt(cantidad)
                });
            });
            $('#articulosMoldal').modal('hide');
        }

        function agregarCategoriasAlCupon() {
            agregarCategoriasAlCupon = [];

            $('#categoriasTable input[type=checkbox]:checked').each(function () {
                var idCategoria = $(this).attr('id');
                categoriasSeleccionadas.push(parseInt(idCategoria));
            });
            console.log(categoriasSeleccionadas);
            $('#categoriasModal').modal('hide');
        }

        function editarCupon() {

            if (detalles.length == 0) {
                $('#articulosTable input[type=checkbox]:checked').each(function () {
                    var idArticulo = $(this).attr('id');
                    var cantidad = $(this).closest('tr').find('input[type=number]').val();
                    detalles.push({
                        Id_ArticuloAsociado: parseInt(idArticulo),
                        Cantidad: parseInt(cantidad)
                    });
                });
                $('#articulosMoldal').modal('hide');
            }

            $('#error-message').text("");

            var form = document.getElementById('cuponForm');
            var formData = new FormData(form);

            formData.append('Descripcion', $('#Descripcion').val());
            formData.append('PorcentajeDto', $('#PorcentajeDto').val());
            formData.append('FechaInicio', $('#FechaInicio').val());
            formData.append('FechaFin', $('#FechaFin').val());
            formData.append('TipoCupon', document.getElementById('tipoCuponSelect').value);

            formData.append('EndPoint', 'EditarCupon');

            formData.append('Detalle', JSON.stringify(detalles));

            formData.append('CategoriasSeleccionadas', categoriasSeleccionadas);

            console.log(formData);

            $.ajax({
                url: '@Url.Action("AltaOEditCupon", "Cupon")',
                type: 'POST',
                data: formData,
                processData: false,
                contentType: false,
                success: function (response) {
                    if (response.success) {

                        window.location.href = '/Cupon/Index';
                        sessionStorage.setItem('successMessage', response.message);

                        $('#success-message').removeClass().
                            addClass('text-danger').text(response.message);

                    } else if (!response.success) {

                        $('#error-message').removeClass().
                            addClass('text-danger').text(response.message);
                    }

                },
                error: function (response) {

                    if (response.responseJSON && response.responseJSON.error) {

                        $('#error-message').removeClass().
                            addClass('text-danger').text("Error al crear el cupón.");
                    } else {

                        $('#error-message').removeClass().
                            addClass('text-danger').text("Error al crear el cupón ERROR FALSE 2.");
                    }
                }
            });
        }
    </script>
}

AdministradorPedidosApp/Views/Cupon/Index.cshtml
@model IEnumerable<AdministradorPedidosApp.Models.CuponModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/css/registro-delete.css" rel="stylesheet" />
<link href="~/css/cupon-delete.css" rel="stylesheet" />

@if(TempData["Error"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["Error"]
    </div>
}
else
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <div id="success-message" style="margin: 5px;"></div>
    <input type="text" id="articulosSearchIndex" class="form-control" placeholder="Buscar Cupón..." />
    <table class="table">
        <thead>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Descripcion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PorcentajeDto)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FechaInicio)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FechaFin)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TipoCupon)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Activo)
                </th>
                <th>
                    Acción
                </th>
            </tr>
        </thead>
        <tbody id="articulosIndexTableBody">
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id_Cupon)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PorcentajeDto)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FechaInicio)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FechaFin)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TipoCupon)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Activo)
                    </td>
                    <td>
                        <button class="btn btn-secondary btn-secondary-k" id="" data-id="@item.Id_Cupon" data-bs-toggle="modal" data-bs-target="#modal-delete-registro-@item.Id_Cupon">Eliminar</button>
                        @* Modal de eliminar *@
                        <div class="modal fade" id="modal-delete-registro-@item.Id_Cupon" tabindex="-1" role="dialog" aria-labelledby="modal-delete-registroLabel" aria-hidden="true">
                            <div class="modal-dialog modal-lg" role="document">
                                <div class="modal-content k-modal-content">
                                    <div class="modal-body k-modal-body">
                                        <p>¿Seguro que quieres eliminar el cupón con ID: @item.Id_Cupon?</p>
                                    </div>
                                    <div class="modal-footer k-modal-footer">
                                        <h5 class="modal-title" id="modal-errorLabel-@item.Id_Cupon"></h5>
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                                        <button type="button" class="btn btn-danger" onclick="eliminarCupon(@item.Id_Cupon)">Confirmar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a class="btn btn-secondary btn-secondary-k" asp-controller="Cupon" asp-action="Edit" asp-route-id="@item.Id_Cupon">Editar</a>
                    </td>
                    @* Modal de confirmación de eliminación exitosa *@
                    <div class="modal fade" id="modal-success" tabindex="-1" role="dialog" aria-labelledby="modal-successLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content k-modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="modal-successLabel"></h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </tr>
            }
        </tbody>
    </table>
}

@section scripts {
    <script src="~/js/articulos/searchcategoriasinmodal.js"></script>

    <script>
        var successMessage = sessionStorage.getItem('successMessage');
        if(successMessage){
            $('#success-message').removeClass()
                .addClass('text-success').text(successMessage);
            sessionStorage.removeItem('successMessage');
        }
    </script>

    <script>
        $(document).ready(function () {
            // Evento para detectar cuándo se abre un modal
            $('body').on('shown.bs.modal', '.modal', function () {
                var modalId = $(this).attr('id');
                var cuponId = modalId.replace('modal-delete-registro-', '');
                $('#modal-errorLabel-' + cuponId).text(''); // Limpiar el texto al abrir el modal
            });

            // Evento para detectar cuándo se cierra un modal
            $('body').on('hidden.bs.modal', '.modal', function () {
                var modalId = $(this).attr('id');
                var cuponId = modalId.replace('modal-delete-registro-', '');
                $('#modal-errorLabel-' + cuponId).text(''); // Limpiar el texto al cerrar el modal
            });
        });

        function eliminarCupon(idCupon) {
            console.log(idCupon);

            $.ajax({
                url: "http://localhost:5203/api/Cupones/" + idCupon,
                type: "DELETE",
                success: function (response) {
                    if (response) {
                        // Cerrar el modal de confirmación
                        $('#modal-delete-registro-' + idCupon).modal('hide');
                        // Mostrar el modal de éxito
                        $('#modal-successLabel').text(response);
                        $('#modal-success').modal('show');

                        setTimeout(function () {
                            location.reload();
                        }, 2000);
                    }
                },
                error: function (xhr) {
                    var errorMessage;
                    if (xhr.status === 400) {
                        errorMessage = xhr.responseText; // Capturar el mensaje de error
                    } else {
                        errorMessage = "Error al comunicarse con el Web Service de Cupones.";
                    }
                    $('#modal-errorLabel-' + idCupon).removeClass().addClass('text-danger').text(errorMessage);
                }
            });
        }
    </script>
}

AdministradorPedidosApp/Views/Cupon/_ArticulosCuponPartial.cshtml
@model AdministradorPedidosApp.Models.CuponModel
<!-- Modal -->
<div class="modal fade" id="categoriasModal" tabindex="-1" role="dialog" aria-labelledby="categoriasModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="categoriasModalLabel">Seleccionar Artículos</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <input type="text" id="categoriaSearch" class="form-control" placeholder="Buscar Artículos..." />
                <div id="categoriasTableContainer">
                    <table class="table table-striped mt-3" id="articulosTable">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nombre</th>
                                <th>Cantidad</th>
                                <th>Seleccionar</th>
                            </tr>
                        </thead>
                        <tbody id="categoriasTableBody">
                            @foreach (var articulo in ViewBag.Articulos)
                            {
                                <tr>
                                    <td>@articulo.Id_Articulo</td>
                                    <td>@articulo.Nombre</td>
                                    <td>
                                        <input type="number" class="form-control" name="Detalle[@articulo.Id_Articulo].Cantidad" value="1">
                                    </td>
                                    <td>
                                        <input type="checkbox" id="@articulo.Id_Articulo" name="ArticulosSeleccionados" value="@articulo.Id_Articulo"
                                        @(Model.ArticulosSeleccionados.Contains(articulo.Id_Articulo) ? "checked" : "")>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" onclick="agregarDetallesCupon()">Guardar Selección</button>
            </div>
        </div>
    </div>
</div>

AdministradorPedidosApp/Views/Cupon/_ArticulosCuponPartialEdit.cshtml
@model AdministradorPedidosApp.Models.CuponModel
<!-- Modal -->
<div class="modal fade" id="categoriasModal" tabindex="-1" role="dialog" aria-labelledby="categoriasModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="categoriasModalLabel">Seleccionar Artículos</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <input type="text" id="categoriaSearch" class="form-control" placeholder="Buscar Artículos..." />
                <div id="categoriasTableContainer">
                    <table class="table table-striped mt-3" id="articulosTable">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nombre</th>
                                <th>Cantidad</th>
                                <th>Seleccionar</th>
                            </tr>
                        </thead>
                        <tbody id="categoriasTableBody">
                            @foreach (var articulo in ViewBag.Articulos)
                            {
                                <tr>
                                    <td>@articulo.Id_Articulo</td>
                                    <td>@articulo.Nombre</td>
                                    <td>
                                        <input type="number" min="1" class="form-control" name="Detalle[@articulo.Id_Articulo].Cantidad" value="@articulo.Cantidad">
                                    </td>
                                    <td>
                                        <input type="checkbox" id="@articulo.Id_Articulo" name="ArticulosSeleccionados" value="@articulo.Id_Articulo"
                                        @(Model.ArticulosSeleccionados.Contains(articulo.Id_Articulo) ? "checked" : "")>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" onclick="agregarDetallesCupon()">Guardar Selección</button>
            </div>
        </div>
    </div>
</div>

AdministradorPedidosApp/Views/Cupon/_EliminarCuponModalPartial.cshtml
@model AdministradorPedidosApp.Models.CuponModel
<!-- Modal -->

<div id="modal" class="modal-delete-registro">
    <div class="modal-content">
        <span class="close">&times;</span>
        <p>¿Seguro que quieres eliminar el registro?</p>
        <button id="cancelBtn" class="btn">Cancelar</button>
        <button id="confirmBtn" class="btn">Confirmar</button>
    </div>
</div>