AdministradorPedidosApp/Controllers/CategoriaCuponController.cs
using AdministradorPedidosApp.Interfaces;
using AdministradorPedidosApp.Models.DTOs;
using Microsoft.AspNetCore.Mvc;

namespace AdministradorPedidosApp.Controllers
{
    public class CategoriaCuponController : Controller
    {
        private readonly ICategoriaCuponService _categoriaCuponService;

        public CategoriaCuponController(ICategoriaCuponService categoriaCuponService)
        {
            _categoriaCuponService = categoriaCuponService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                return View(await _categoriaCuponService.GetCategoriasCupones());
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return View();
            }
        }

        public async Task<IActionResult> Create()
        {
            var categoriaCuponModel = new CategoriaDTO();
            return View(categoriaCuponModel);
        }

        [HttpPost]
        public async Task<IActionResult> AltaCategoriaCupon([FromForm] CategoriaDTO categoriaCupon)
        {
            try
            {
                var result = await _categoriaCuponService.AltaCategoriaCupon(categoriaCupon);
                return Json(new { success = true, message = result });
            }
            catch(Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }
    }
}

AdministradorPedidosApp/Views/CategoriaCupon/Create.cshtml
@model AdministradorPedidosApp.Models.DTOs.CategoriaDTO

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/css/modalselectcategoriasarticulos.css" rel="stylesheet" />

<h1>Create</h1>

<h4>Categoría de Cupones</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form id="categoriaCupon-form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <br />
        </form>

        <div class="form-group">
            <button class="btn btn-primary" onclick="crearCategoriaCupon()">Crear</button>
        </div>
        <div id="error-message" style="margin-top: 5px;"></div>
    </div>
</div>

@section Scripts{
    <script>
        function crearCategoriaCupon(){
            const valorNombre = $('#Nombre').val();
            
            if (valorNombre === "") {
                alert("Completar todos los campos, pelotudo.");
                return;
            }

            var form = document.getElementById('categoriaCupon-form');
            var formData = new FormData(form);

            $.ajax({
                url: '@Url.Action("AltaCategoriaCupon", "CategoriaCupon")',
                type: 'POST',
                data: formData,
                processData: false,
                contentType: false,
                success: function(response){
                    if (response.success) {
                        window.location.href = '/CategoriaCupon/Index';
                        sessionStorage.setItem('successMessage', response.message);

                        $('#error-message').removeClass().
                            addClass('text-danger').text(response.message);
                    } else if (!response.success) {
                        $('#error-message').removeClass().
                            addClass('text-danger').text(response.message);
                    }
                },
                error: function(response){
                    if (response.responseJSON && response.responseJSON.error){
                        $('#error-message').removeClass().
                            addClass('text-danger').text("Error al dar de alta la Categoría.");
                    } else {
                        $('#error-message').removeClass().
                            addClass('text-danger').text("Error al dar de alta la Categoría.");
                    }
                }
            })
        }
    </script>
}

AdministradorPedidosApp/Views/CategoriaCupon/Index.cshtml
@model IEnumerable<AdministradorPedidosApp.Models.DTOs.CategoriaDTO>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if(TempData["Error"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["Error"]
    </div>
}
else
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <div id="success-message" style="margin: 5px;"></div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id_Categoria">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id_Categoria">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id_Categoria">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

}

@section Scripts {
    <script>
        var successMessage = sessionStorage.getItem('successMessage');
        if (successMessage) {
            $('#success-message').removeClass()
                .addClass('text-success').text(successMessage);
            sessionStorage.removeItem('successMessage');
        }
    </script>
}